### ISSUE TITLE
audio in ABX test cannot be played when click Play button

### ISSUE THREAD

**Issue by Yablon** [descriptinc/audiotools#100]
Hi, following the instructions and codes in your [documentation](https://descriptinc.github.io/audiotools/tutorials/listening_tests.html) for creating listening tests, I can setup the gradio service successfully but when clicking at the "Play A" or "Play B", the audio cannot be played out. How can I fix this ? I tried to remove the js codes and set gr.Audio visible to True, it works for now though.

**Comment by pseeth** [comment]
This will be fixed once #90 is merged.
